
services:

  go-intro:
    image: go-intro:1.22.3-bookworm
    build:
      context: .
      dockerfile: go-intro.dockerfile
    container_name: go-intro
    hostname: go-intro
    environment:
      - TZ=Europe/Berlin
    volumes:
      - type: bind
        source: ./
        target: /home/gopher/go-intro
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: unless-stopped
